### ISSUE TITLE
Inclusion of a GPL3 library requires all code to become GPL3

### ISSUE THREAD

**Issue by dangerousfood** [sushiswap/kashi-lending#33]
GPL3 is infectious; any code that uses a GPL library automatically becomes GPL as well.

https://github.com/sushiswap/kashi-lending/blob/94d9bfcadcdf5157e7bb14904cf8495ad1ca2e4f/contracts/libraries/FixedPoint.sol#L1

**Comment by casualjim** [comment]
The only code that is subjected to GPL3 is the code covered by it. 

It makes no sense to say that any software running on linux that uses libc is by extension gpl3.  If you modify gpl3 licensed code you have to distribute the source for it and if you package your code you need to distribute the source of the gpl3 licensed parts.

**Comment by boringcrypto** [comment]
This repo contains multiple 'projects' or 'executables' or whatever you'd like to call it. Neither BentoBox nor Kashi use this library and are therefore not in scope. This library is used by one of the example swappers, so that one should be GPL instead of MIT.

**Comment by jrhea** [comment]
> The only code that is subjected to GPL3 is the code covered by it.
> 
> It makes no sense to say that any software running on linux that uses libc is by extension gpl3. If you modify gpl3 licensed code you have to distribute the source for it and if you package your code you need to distribute the source of the gpl3 licensed parts.

Your argument doesn't apply bc Libc is LGPL (not GPL3) and that is quite different. This text from the LGPL license is very clear:

`A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a “work that uses the Library”. Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.`

**Comment by boringcrypto** [comment]
Anyway, BentoBox.sol and KashiPair.sol remain copyrighted code.

The only place the GPL3 code is used is in some of the swappers. The swappers are like plug-ins into VS Code... If I create a new plug-in for VS Code that is GPL3 and make it available for VSCode, that doesn't make VS Code GPL3.

Please revert to the correct licensing.

**Comment by levx-io** [comment]
@boringcrypto where is/was the license doc?

**Comment by boringcrypto** [comment]
It's here: https://github.com/sushiswap/kashi-lending/blob/94d9bfcadcdf5157e7bb14904cf8495ad1ca2e4f/contracts/KashiPair.sol#L11

**Comment by boringcrypto** [comment]
To be able to use it, Sushi received a license as per the deal outlined in my Medium post. While not written in legal jargon, it's still very much a legal contract I think. An offer was made and accepted, something of value was exchanged and consideration paid. But I'm happy to sign a more legalese doc granting Sushi this license:

"A perpetual unrestricted license will be granted to Sushi but only for the use within the Sushi ecosystem."

I'm also happy to open source the code if the community decides that is what they want, which the exception of using the code to create a stablecoin (unless Abracadabra community is ok with it)

**Comment by levx-io** [comment]
@boringcrypto your medium articles can be edited any time by you

**Comment by levx-io** [comment]
https://snapshot.org/#/sushigov.eth/proposal/QmZTwyGgJb7k6RofLJW2hMy2yMaE2p2zyE6hGbdaWHmUUY

1. Snapshot vote didn't include any license at all
2. Your delivery of bentobox was delayed more than 20 days at least(`every day delayed after that will reduce success fee by 5%.`)

**Comment by boringcrypto** [comment]
Which meant I had no incentive left to deliver, which led to a renegotiation with 0xMaki in which this was all sorted out. Anyway, what are you trying to achieve here? What is it that you want me to do? Maybe I can help?

**Comment by levx-io** [comment]
Where is the record of that renegotiation? Did the community approve it?

**Comment by levx-io** [comment]
I just want everything right and fair
