### ISSUE TITLE
Missing proxy factory?

### ISSUE THREAD

**Issue by wjmelements** [sushiswap/kashi-lending#6]
`masterContract` is immutable and equal to `address(this)` so no reason to do `KashiPair(masterContract).swappers(swapper)`; you can just access your storage directly.

**Comment by wjmelements** [comment]
> @notice The constructor is only used for the initial master contract. Subsequent clones are initialised via `init`.

oic there is some proxy factory. Where can I find this factory contract?

**Comment by boringcrypto** [comment]
It uses the BentoBox as factory

**Comment by wjmelements** [comment]
Nice thx
```
contract MasterContractManager is BoringOwnable, BoringFactory
```
